version: "3.5"

# you have to generate the server.key and server.crt files
# if you login to pgadmin, use "postgres" as the host name

services:
  postgres:
    container_name: postgres_container
    image: postgres
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./server.crt:/var/lib/postgresql/server.crt
      - ./server.key:/var/lib/postgresql/server.key
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_ENABLE_TLS: "True"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./server.cert:/certs/server.cert:ro
      - ./server.key:/certs/server.key:ro
    ports:
      - "${PGADMIN_PORT:-5050}:443"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver:

volumes:
  postgres:
  pgadmin:
